### ISSUE TITLE
CV Homework

### ISSUE THREAD

**Issue by Hayao-1111** [sast-summer-training-2023/sast2023-cv#2]
仓库地址：[https://github.com/Hayao-1111/CV_homework](https://github.com/Hayao-1111/CV_homework)

提交人：孙鑫礼
学号：2022311113

**Comment by zhuhz22** [comment]
评价
环境配置与安装:15pts;
数据预处理:15pts;
模型框架搭建:40pts，似乎少了一个问题（What do these two lines of code do?）
模型训练与可视化 20pts (缺最终训练的结果5pts~~节省算力为地球环保做贡献~~)
final：90pts(~~整体效果比助教好多了~~)
